services:
  - type: web
    name: prag-drishti
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /api/cases
    envVars:
      - key: PORT
        value: 8000
